targets:
  $default:
    builders:
      hive_generator|hive_generator:
        generate_for:
          - lib/model/*.dart
        options:
          # Generate adapters for Hive models
          auto_dispose: true